### ISSUE TITLE
Add code to View elements in the database

### ISSUE THREAD

**Issue by CaptainPig-gy** [CS180-spring/cs180-22-teamone#22]

**Comment by Tinoco451** [comment]
Behavior Driven Test Case:

Scenario: The user wants to view the elements that are inside the database.

Given: The application is running and connected to a database 

When the user clicks on the "View elements" button

Then the application displays a list of all elements in the database

And each element is displayed with its corresponding ID, name, and the other relevant information

And the list is sorted in ascending order by ID

And the developer can click on an element in the list to view its details

**Comment by HettyPatel** [comment]
Done!

**Comment by CaptainPig-gy** [comment]
Reviewed by Jeff
