### ISSUE TITLE
Add code to remove elements in the database

### ISSUE THREAD

**Issue by CaptainPig-gy** [CS180-spring/cs180-22-teamone#23]
Story: As a user I want to be able to remove elements from a database

**Comment by penwin2468** [comment]
Unit Test
- Remove an element that doesn't exist
- Remove a duplicate element
- Remove only a part of an element (aka one or a certain number of fields)

Behavior Driven Test Case

**Scenario:** I want to remove one or more elements from my database

**Given**: I am at the home screen for my interface

**When:** I select the prompt to remove an entry

**Then:** The program should list all entries with their ID and fields

**Then:** I should choose which entry I want to remove

**And:** The program will delete the entry without any option for recovery

**And:** The program will prompt me to delete another entry

**Then:** When I am ready to stop, I will tell the program to stop.

**Comment by CaptainPig-gy** [comment]
Reviewed by Jeff
