### ISSUE TITLE
Create input code to add elements to the database

### ISSUE THREAD

**Issue by CaptainPig-gy** [CS180-spring/cs180-22-teamone#25]
Story: add and remove elements from database

Reviewer: Het Patel

**Comment by dtalmood** [comment]
**Scenario:**: User enters the Data Base User interface 

**Given** I have access to the main menu  

**When**: I enter "1" I should be able to "Create a new record" 

**And**:  I am prompted to enter as many fields as I want  

**And**:  I enter nothing when I no longer want to input any more fields 

**And**:  I then input data into the fields I just created and once all fields data is inserted i am done

**Comment by HettyPatel** [comment]
Done!
