### ISSUE TITLE
Search through all databases(all json files)

### ISSUE THREAD

**Issue by HettyPatel** [CS180-spring/cs180-22-teamone#42]
Unit Test

Look for an element in all databases.

Scenario: I want to look for an element all json files.

Given: I am at the home screen on the main UI

When: I select the prompt to search through all databases.

Then: Program asks me what field I would like to search for.

Then: I type in the field.

Then: Program asks me for a specific value for that field. 

Then: The program searches through all databases and shows me all entries that match the description. 

Then: I am returned back to my main menu.

**Comment by CaptainPig-gy** [comment]
Reviewed by Jeff
