### ISSUE TITLE
Error handling to catch users  mistakes when creating, searching, selecting Databases.

### ISSUE THREAD

**Issue by dtalmood** [CS180-spring/cs180-22-teamone#47]
Unit Test

1. Ensure if the user  just starts the program to shoot an error that there are no existing data bases 

2. Ensure that if the user tries switching to a data base which does not exist  it shoots an error 

3. Ensure that if there user Searches for ID that does not exist it shoots and error. 
_________________________________________________________________________________________________________________

Scenario: User tries to enter a data base of non existing data base 

Given:  The program has no record of a database existing 

When:  The user initially enters the program 

Then: The user in menu types number to switch databse s

Then: The user types a name of a data base 

Then: Program shoots error stating that the database inserted does not exist and prompting them to create one.

**Comment by CaptainPig-gy** [comment]
Reviewed by Jeff
