### ISSUE TITLE
Give all Data Based on some specified Field

### ISSUE THREAD

**Issue by dtalmood** [CS180-spring/cs180-22-teamone#54]
User Story: [#7](https://github.com/CS180-spring/cs180-22-teamone/issues/7)

Scenario: User enters program and there is a Data Base with 3 fields(Name, Age, Sex)

Given: I have access to the main menu

When: I enter the user program 

And: I enter 10 to go into the function for "Search Field "

And: The program prints the field of the current Data Base

And: The user then types name of the field they want to search and hit enter 

And: All section that meet the requirements of field are printed on screen

**Comment by CaptainPig-gy** [comment]
Reviewed by Jeff
