### ISSUE TITLE
Add confirmation prompt for deleting

### ISSUE THREAD

**Issue by Tinoco451** [CS180-spring/cs180-22-teamone#56]
User Story #55 

Scenario: User adds a record and wishes to delete it

Given: I have access to the main menu

When: I enter the user program

And: I press 8 to enter the delete record function

And: The program requests confirmation for deleting a record

And: The user then confirms that they wish to delete a certain record

And: The record is now gone from the Database

**Comment by CaptainPig-gy** [comment]
Reviewed by Jeff
