### ISSUE TITLE
Add sorting database function

### ISSUE THREAD

**Issue by Tinoco451** [CS180-spring/cs180-22-teamone#57]
User Story #58 
Scenario: The user wants to sort elements in database in ascending/descending order

Given: I have access to the main menu

When: I enter the user program

And: I press a certain key to enter the sort function

And: The program request  what type of sorting the user wants

And: The user selects a type of sorting 

And: The database is now sorted in the selected order

**Comment by CaptainPig-gy** [comment]
Reviewed by Tinoco
