### ISSUE TITLE
Create a basic login system

### ISSUE THREAD

**Issue by HettyPatel** [CS180-spring/cs180-22-teamone#59]
User Story #61 

Unit Test

Be able to create an account
Be able to log in to your account

Scenario: I want to create an account and log in

Given: I am at the home screen I see a create an account option. 

Then: I select create an account and fill in my information.

Then: Hello "UserName" Your account has been created message pops up. 

Then: I am logged in and can continue to use my account as normal.

**Comment by CaptainPig-gy** [comment]
Reviewed by Jeff
