### ISSUE TITLE
Add role permissions

### ISSUE THREAD

**Issue by Tinoco451** [CS180-spring/cs180-22-teamone#73]
User Role #68

**Comment by penwin2468** [comment]
Be able to assign roles to certain users working on the same database
Be able to change, remove, and redistribute roles among users.
Be able to change what each role is allowed to do.


Scenario: I want to prevent my team members from changing files that they are not working on

Given: Everyone on my team is assigned a specific task and only needs to access the files related to their task

Then: I will assign team leaders and members with different roles, such that team members can only edit the files that are related to their task.

Then: Team leaders will be able to add and change the files that the team is working on, but are not able to delete files from other teams.

Then: I can manage each individual team from my Master role
