### ISSUE TITLE
Add input data validation check

### ISSUE THREAD

**Issue by Tinoco451** [CS180-spring/cs180-22-teamone#74]

**Comment by penwin2468** [comment]
Rule #67 

Be able to check the database for corrupt data, duplicates, or errors in entry


Given: I just imported a database from a CSV and am not sure if the import correctly worked.

And: I want to check to make sure there are no corruptions or errors in the database

Then: I will run a validation function that will go through the database to ensure there are no empty or corrupted entries

Then: The function will remove them
